const { test, before, after } = require('node:test')
const assert = require('node:assert/strict')
const mongoose = require('mongoose')
const { MongoMemoryServer } = require('mongodb-memory-server')
const request = require('supertest')
const { io: connect } = require('socket.io-client')
const { once } = require('node:events')
const { createApp } = require('../src/app')
const Utilisateur = require('../src/models/Utilisateur')
const Score = require('../src/models/Score')
let mongo, server, app, io, address
const sockets = []
const token = (html) => html.match(/name="_csrf" value="([^"]+)"/)[1]
async function register(name) {
  const agent = request.agent(app)
  const page = await agent.get('/inscription')
  const response = await agent.post('/utilisateur/inscription').type('form').send({ _csrf: token(page.text), nomUtilisateur: name, email: `${name}@example.test`, mdp: 'abcdefgh1234', mdp2: 'abcdefgh1234' })
  assert.equal(response.status, 302)
  const cookie = response.headers['set-cookie'][0].split(';')[0]
  return { agent, cookie }
}
async function socket(namespace, cookie) {
  const client = connect(address + namespace, { extraHeaders: { Cookie: cookie }, transports: ['websocket'], forceNew: true })
  sockets.push(client)
  await once(client, 'connect')
  return client
}
before(async () => {
  mongo = await MongoMemoryServer.create()
  await mongoose.connect(mongo.getUri())
  await Promise.all([Utilisateur.init(), Score.init()])
  ;({ app, server, io } = createApp({ secret: 'a'.repeat(48) }))
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve))
  address = `http://127.0.0.1:${server.address().port}`
})
after(async () => {
  sockets.forEach((client) => client.disconnect())
  await new Promise((resolve) => io.close(resolve))
  await mongoose.disconnect()
  await mongo.stop()
})
test('accès protégé, erreurs et protection des formulaires', async () => {
  assert.equal((await request(app).get('/salon')).headers.location, '/connexion')
  assert.equal((await request(app).get('/salon/salonDeJeu/missing')).status, 302)
  assert.equal((await request(app).get('/inexistant')).status, 404)
  assert.equal((await request(app).post('/utilisateur/inscription').send({})).status, 403)
  const anonymous = connect(address + '/jeu', { transports: ['websocket'], forceNew: true })
  const [error] = await once(anonymous, 'connect_error')
  assert.match(error.message, /Connexion/)
  anonymous.disconnect()
})
test('inscription, normalisation, validation et connexion', async () => {
  const agent = request.agent(app)
  const page = await agent.get('/inscription')
  assert.equal((await agent.post('/utilisateur/inscription').type('form').send({ _csrf: token(page.text), nomUtilisateur: '<script>', email: 'bad', mdp: 'abc', mdp2: 'abc' })).status, 422)
  await register('ALICE')
  const user = await Utilisateur.findOne({ nomUtilisateur: 'alice' })
  assert.ok(user)
  assert.notEqual(user.mdp, 'abcdefgh1234')
  const login = request.agent(app)
  const loginPage = await login.get('/connexion')
  assert.equal((await login.post('/utilisateur/connexion').type('form').send({ _csrf: token(loginPage.text), email: 'ALICE@EXAMPLE.TEST', mdp: 'abcdefgh1234' })).headers.location, '/salon')
})
test('un joueur ne peut modifier le profil d’un autre', async () => {
  const { agent } = await register('profiltest')
  const victim = await Utilisateur.findOne({ nomUtilisateur: 'alice' })
  const profile = await agent.get('/profil')
  await agent.post('/utilisateur/editer-profil').type('form').send({ _csrf: token(profile.text), idUtilisateur: victim.id, nouveauNomUtilisateur: 'modifie' })
  assert.equal((await Utilisateur.findById(victim.id)).nomUtilisateur, 'alice')
  assert.ok(await Utilisateur.exists({ nomUtilisateur: 'modifie' }))
})
test('salon à deux, événements malformés, score lié au compte et nettoyage', async () => {
  const a = await register('joueur_a'), b = await register('joueur_b'), c = await register('joueur_c')
  const lobby = await a.agent.get('/salon')
  const response = await a.agent.post('/salon/salonDeJeu/room').type('form').send({ _csrf: token(lobby.text), room: '__proto__' })
  assert.match(response.headers.location, /salonDeJeu\/[a-f0-9-]+$/)
  const room = response.headers.location.split('/').pop()
  const one = await socket('/jeu', a.cookie), two = await socket('/jeu', b.cookie), three = await socket('/jeu', c.cookie)
  one.emit('startGame')
  one.emit('scoreFinDeJeu', null)
  assert.equal(await one.emitWithAck('join', { room }), undefined)
  assert.equal(await two.emitWithAck('join', { room }), undefined)
  assert.match(await three.emitWithAck('join', { room }), /complet/)
  assert.equal((await c.agent.get(response.headers.location)).status, 409)
  const init = once(two, 'init')
  one.emit('startGame')
  await init
  const moved = once(two, 'deplacementMonJoueur')
  one.emit('deplacementMonJoueur', { id: 'forged', etat: { runningRight: true } })
  assert.equal((await moved)[0].id, one.id)
  assert.match(await one.emitWithAck('scoreFinDeJeu', { monScore: -5, scoreAutreJoueur: 1 }), /invalide/)
  assert.equal(await one.emitWithAck('scoreFinDeJeu', { monNom: 'forged', monScore: 8, scoreAutreJoueur: 5, nomUtilisateurAutreJoueur: 'forged' }), undefined)
  assert.match(await one.emitWithAck('scoreFinDeJeu', { monScore: 8, scoreAutreJoueur: 5 }), /invalide/)
  const score = await Score.findOne({ monNom: 'joueur_a' })
  assert.equal(score.nomUtilisateurAutreJoueur, 'joueur_b')
  assert.equal(String(score.monJoueurId), String((await Utilisateur.findOne({ nomUtilisateur: 'joueur_a' }))._id))
  assert.equal((await a.agent.get('/stats')).status, 200)
  one.disconnect(); two.disconnect(); three.disconnect()
  await new Promise((resolve) => setTimeout(resolve, 50))
  assert.equal(app.salons[room], undefined)
})
test('discussion liée à la session et messages bornés', async () => {
  const a = await register('chat_a'), b = await register('chat_b')
  const one = await socket('/discussion', a.cookie), two = await socket('/discussion', b.cookie)
  await one.emitWithAck('join', { nomUtilisateur: 'forged' })
  await two.emitWithAck('join', {})
  const message = once(two, 'message')
  assert.equal(await one.emitWithAck('envoyerMessage', '<img src=x onerror=alert(1)>'), undefined)
  assert.equal((await message)[0].nomUtilisateur, 'chat_a')
  assert.match(await one.emitWithAck('envoyerMessage', 'x'.repeat(1001)), /caractères/)
  assert.match(await one.emitWithAck('envoyerMessage', {}), /caractères/)
  const page = await a.agent.get('/profil')
  assert.equal((await a.agent.post('/utilisateur/deconnexion').type('form').send({ _csrf: token(page.text) })).headers.location, '/connexion')
  assert.equal((await a.agent.get('/profil')).status, 302)
})
